---
- name: detect latest v2ray plugin release
  github_release:
    repository: shadowsocks/v2ray-plugin
    release: "{{ srv_ss_v2ray_version }}"
    template: "{download_url}/v2ray-plugin-linux-amd64-{ver}.tar.gz"
    creates: "{{ srv_ss_v2ray_binary }}"
    reinstall: "{{ srv_ss_v2ray_upgrade |bool }}"
  register: _ss_v2ray_release

- name: download archived v2ray plugin binary
  unarchive:
    remote_src: true
    src: "{{ _ss_v2ray_release.url }}"
    dest: "{{ srv_ss_v2ray_binary |dirname }}"
  when: _ss_v2ray_release is changed

- name: move v2ray plugin binary in-place
  command:
    argv:
      - mv
      - "{{ srv_ss_v2ray_binary }}_linux_amd64"
      - "{{ srv_ss_v2ray_binary }}"
  when: _ss_v2ray_release is changed
...
